config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :message_or_image, presence: true
  mount_uploader :image, ImageUploader
end

private
def message_or_image
  message.presence or image.presence
end

app/models/user.rb
class User < ApplicationRecord
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  scope :search_name, -> (keyword, current_user){where('name LIKE(?)', "%#{keyword}%").where.not(id: current_user)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_out_path_for(resource)
  '/users/sign_in'
end

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :move_to_sign_in

  def index
    @groups = current_user.groups
    @message = Message.new
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group.id), notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを修正しました'
    else
      render :edit
    end
  end

private
  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end


  def group_params
    params.require(:group).permit(:name, user_ids:[])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :move_to_sign_in
  before_action :set_group, only: [:index, :create]

  def index
    @messages = @group.messages.order(created_at: :ASC).includes(:user)
    @message = Message.new
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group.id) }
        format.json
      end
    else
      flash.now[:alert] = 'メッセージか画像を入力して下さい'
      render :index
    end
  end

private

  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end

  def message_params
    params.require(:message).permit(:message, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.search_name(params[:keyword], current_user)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      flash[:notice]= "success"
      redirect_to root_path
    else
      render :edit
    end
  end

private
  def user_params
    params.permit(:name, :email)
  end

end

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  - if @group.errors.any?
    .chat-group-form__errors
      %h2 #{@group.errors.full_messages.count}件のエラーが発生しました。
      %ul
        -@group.errors.full_messages.each do |message|
          %li
            =message
  = render "layouts/edit_group"

app/views/groups/index.html.haml
%body
  /= render "layouts/flash"
  .group_box
    .group_box__upper
      .group_box__upper-content
        %p
        テスト
        %i.fa.fa-cogs
        = link_to new_group_path do
          %i.fa.fa-pencil-square-o
    .group_box__middle_list
      -@groups.each do |group|
        .group_box__middle_list_name
          %h1
          =group.name
          %p まだメッセージはありません。

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  - if @group.errors.any?
    .chat-group-form__errors
      %h2 #{@group.errors.full_messages.count}件のエラーが発生しました。
      %ul
        -@group.errors.full_messages.each do |message|
          %li
            =message
  = render "layouts/new_group"

app/views/groups/untitled.html.haml
  %form#new_chat_group.new_chat_group{"accept-charset" => "UTF-8", :action => "/chat_groups", :method => "post"}
    .chat-group-form__errors
      %h2
        1件のエラーが発生しました。
        %ul
          %li エラーです
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_name"} グループ名
      .chat-group-form__field--right
        %input#chat_group_name.chat-group-form__input{:name => "chat_group[name]", :placeholder => "グループ名を入力してください", :type => "text"}/
    .chat-group-form__field.clearfix
        -if @group.error.any?
    .chat-group-form__errors
      %h2 1件のエラーが発生しました。
      %ul
        %li エラーです
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
        /
          <div id='chat-group-users'>
          <div class='chat-group-user clearfix' id='chat-group-user-22'>
          <input name='chat_group[user_ids][]' type='hidden' value='22'>
          <p class='chat-group-user__name'>seo_kyohei</p>
          </div>
          </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        %input.chat-group-form__action-btn{"data-disable-with" => "Save", :name => "commit", :type => "submit", :value => "Save"}/

app/views/layouts/_edit_group.html.haml
= form_for @group do |f|
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, "グループ名", :class => "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, :placeholder => "グループ名を入力して下さい", :class => "chat-group-form__input", :name => "group[name]"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chatn_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-searchfield.chat-group-form__{placeholder: "追加したいユーザー名を入力して下さい" type='text'}/
      %ul#user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__field--right{for: "chat_group_チャットメンバー"}チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        .chat-group-user.clearfix
          %p.chat-group-user_name= current_user.name

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "更新する", class: "chat-group-form__action-btn", name: "commit"

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/_new_group.html.haml
= form_for @group do |f|
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, "グループ名", :class => "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, :placeholder => "グループ名を入力して下さい", :class => "chat-group-form__input", :name => "group[name]"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chatn_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力して下さい", type: 'text'}/
      %ul#user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__field--right{for: "chat_group_チャットメンバー"}チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        .chat-group-user.clearfix
          %p.chat-group-user_name= current_user.name

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "作成する", class: "chat-group-form__action-btn", name: "commit"

app/views/layouts/_top_messages.html.haml
.top_message
      %h1 チャットグループが作成されました。

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatSpace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/index.html.haml
%body
  .group_box
    .group_box__upper
      .group_box__upper-content
        %p
        テスト
        %i.fa.fa-cogs
        = link_to new_group_path do
          %i.fa.fa-pencil-square-o
    .group_box__middle_list
      -current_user.groups.each do |group|
        .group_box__middle_list_name
          = link_to group_messages_path do
            %h1= group.name
            -if group.messages.last
              %p= group.messages.last.message
            -else
              %p まだメッセージがありません。
  .chat_box
    .chat_box__upper
      .chat_box__upper_left
        %h1= @group.name
        %h2 member:test
      .chat_box__upper_right
        %a{href: "/groups/1/edit"} Edit
    .chat_box__middle
      -if @group.messages.present?
        -@group.messages.each do |message|
          .chat_box__middle_message
            %h1= message.user.name
            %a= message.created_at.try(:strftime, "%Y/%m/%d %H時%M分")
            %h2= message.message
            -if message.image.present?
              = image_tag message.image
    .chat_box__bottom
      = form_for [@group, @message] do |f|
        .chat_box__bottom_text
          = f.text_field :message, placeholder: "type a message", class: "chat_box__bottom_text.input", name: "message[message]"
          .chat_box__bottom_text_image
            = f.label :image do
              %i.fa.fa-picture-o
              = f.file_field :image, class: "chat_box__bottom_text_image_hidden"
        .chat_box__bottom_text-button
          = f.submit "Send", class: "chat_box__bottom_text-button.input", name: "commit"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'